### ISSUE TITLE
Error queuing to tasks: DRAINING

### ISSUE THREAD

**Issue by maxfrigge** [assaf/ironium#18]
This is happening running against iron.io.

I am running on version 3.0.1 but this was happening on 2.7.0 before. Basically the queue doesn't work at all - neither sending nor receiving messages.

I have also deleted the MQ2 queue to make sure it's not a compatibility issue. First restarted my ironium application and expected it to setup the queue automatically, which didn't work. Then I created the queue by hand, but it didn't work either.

Here goes the stack:

```
Error: Error queuing to tasks: DRAINING
  at Queue._delayJob$ (/pipeline/source/node_modules/ironium/lib/queues.js:549:19)
  at tryCatch (/pipeline/source/node_modules/ironium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
  at GeneratorFunctionPrototype.invoke [as _invoke] (/pipeline/source/node_modules/ironium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
  at GeneratorFunctionPrototype.prototype.(anonymous function) [as throw] (/pipeline/source/node_modules/ironium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
  at GeneratorFunctionPrototype.invoke (/pipeline/source/node_modules/ironium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
  at run (/pipeline/source/node_modules/ironium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:89:39)
  at /pipeline/source/node_modules/ironium/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
  at flush (/pipeline/source/node_modules/ironium/node_modules/babel-runtime/node_modules/core-js/library/modules/$.microtask.js:17:13)
  at doNTCallback0 (node.js:407:9)
  at process._tickDomainCallback (node.js:377:13)
  at process.wrappedFunction (/pipeline/source/node_modules/newrelic/lib/transaction/tracer/index.js:271:51)
```

**Comment by assaf** [comment]
Ironium 2.x works with MQ2, Ironium 3.x works with MQ3 and Node 4 or later. This stack trace is for Ironium 2.x.

**Comment by maxfrigge** [comment]
I have double checked the version. It seems that one container got stuck in the ci pipeline. I have also created new access token (in case they where not valid for mq2) and explicitly set the host too. One thing I have noticed is that I previously used `projectID`, which seems to have changed to `project_id`. I have updated that too. I have removed all queues and restarted my containers, but queues are not being created by ironium and theres is no messaging happening at all.

**Comment by maxfrigge** [comment]
Ok.. I think I found it. 

In 2.7.0 I was passing config like this

```
ironium.configure({
  ironio: {
    token: 'XXXX'
  }
});
```

But it has changed in 3.0.x to 

```
ironium.configure({
  token: 'XXXX'
});
```

I'll test for a bit and report back if that was really it.

**Comment by maxfrigge** [comment]
Things are running smoothly again.

Is there anything I should keep an eye on that caused the error when I was still using 2.7?

**Comment by assaf** [comment]
Closing: this was a configuration issue.
