### ISSUE TITLE
Error queuing to tasks: Unknown error

### ISSUE THREAD

**Issue by maxfrigge** [assaf/ironium#22]
My logs occasionally contain this error. Looking at the code it seems to be a connection error when posting a job to iron.io. I think those jobs simply get lost and I am not quite sure how to handle those cases. I am actually a bit uncertain if the problem is the iron.io API or something being stuck in ironium or node, because it would seem very unusual that the iron.io API is unreachable for the period of time these errors occur. 

```
Error queuing to tasks: Unknown error
at /pipeline/source/node_modules/ironium/lib/queues.js:173:20
at /pipeline/source/node_modules/iron_mq/lib/client.js:235:18
at APIClient.Client.parseResponse (/pipeline/source/node_modules/iron_core/lib/client.js:251:18)
at /pipeline/source/node_modules/iron_mq/lib/api_client.js:165:16
at Request._callback (/pipeline/source/node_modules/iron_core/lib/client.js:180:20)
at Request.self.callback (/pipeline/source/node_modules/iron_core/node_modules/request/request.js:344:22)
at emitTwo (events.js:100:13)
at Request.emit (events.js:185:7)
at Request.<anonymous> (/pipeline/source/node_modules/iron_core/node_modules/request/request.js:1239:14)
at emitOne (events.js:95:20)
at Request.emit (events.js:182:7)
at IncomingMessage.<anonymous> (/pipeline/source/node_modules/iron_core/node_modules/request/request.js:1187:12)
at emitNone (events.js:85:20)
at IncomingMessage.emit (events.js:179:7)
at endReadableNT (_stream_readable.js:906:12)
at nextTickCallbackWith2Args (node.js:474:9)
at process._tickDomainCallback (node.js:429:17)
at process.wrappedFunction (/pipeline/source/node_modules/newrelic/lib/transaction/tracer/index.js:245:51)
```

**Comment by assaf** [comment]
This is indeed a problem with the Iron.io API

**Comment by maxfrigge** [comment]
Have you ever managed to isolate this case or get more details why it gets stuck? Is it a problem with the API itself or the `iron_mq` package?

**Comment by assaf** [comment]
It always corresponds with something breaking on the side of Iron.io. The last time it happened was Feb 22 2:36 PM Pacific, their dashboard stopped working, and then started showing negative queue sizes.

**Comment by maxfrigge** [comment]
That's about when it happened in my application too.
Mine where happening from: 2016-02-22 23:32 - 2016-02-23 00:41 UTC

I guess the best solution to this would be to collect and retry after a certain time. 

Would you say that it is the developers responsibility and rather not have it handled ironium?
Otherwise I might create a pull request for this, if you don't mind.

**Comment by assaf** [comment]
Developer's responsibility, because the error handling is varied. You can retry, retry with timeout, let something else retry (e.g. if you're queuing one job from another, fail the job and Ironium will retry it), fail and log, fail and report to user, crash the process, etc.

**Comment by maxfrigge** [comment]
Agree... probably too man cases to handle in the lib. Have you ever talked to iron.io about this?

**Comment by assaf** [comment]
We complained before, and they got better at tracking and reporting each and every time IronMQ is misbehaving: https://status.iron.io/history

**Comment by maxfrigge** [comment]
Thanks for the link.. didn't know about the status page. 
Well I close this one.. as it seems that there is nothing you can do about it.
